# Generated by Django 5.0.6 on 2024-06-26 19:26

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="photo",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="avatars"
            ),
        ),
    ]
